### PR TITLE
Add github enterprise as a config point

### PR DESCRIPTION
**Pull request by JeremyTX**

### CODE REVIEW

**Comment by n4bb12** [comment]
Is the PR ready for merge?

**Comment by JeremyTX** [comment]
@n4bb12 I've tested it locally. If you think the code looks good, feel free to merge.

**Comment by n4bb12** [comment]
Unfortunately, this doesn't work.

`https://api.github.com/user` has been changed to `https://github.com/user` and throws a 410 error.

**Comment by JeremyTX** [comment]
Ah, I only tested with the new path GHE. Didn't realize the original one also changed. I'll create another oauth app on public github and check as well. Thanks for the CR.

**Comment by n4bb12** [comment]
@JeremyTX are you still working on this?

**Pull request closed without merging**
