### PR TITLE
Add Github Enterprise as a config point

### PR DESCRIPTION
**Pull request by JeremyTX**

### CODE REVIEW

**Comment by JeremyTX** [comment]
@n4bb12 unfortunately I couldn't get the v4 branch working in time and need to focus my efforts on other projects. I'll be moving forward with just v3 and may get some bandwith later to tackle the upgrade if you haven't done it yet. I do have a minor PR with deprecating the types, but I find that has less value without the subsequent v4 fixes.

I've re-worked the config point logic for GHE and still would like to merge this PR. I've also tested it locally to make sure it still works the the public github api.

**Comment by JeremyTX** [comment]
image

**Comment by n4bb12** [comment]
Thank you 🎺

**Comment by n4bb12** [comment]
https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/1.8.0

**Pull request merged**
